{
    "docstring": "\"\"\"An attempt on a node is made that is not available in the graph.\"\"\"",
    "name": "NodeNotFoundError",
    "namespace": "django.db.migrations.exceptions.NodeNotFoundError",
    "module_name": "django.db.migrations.exceptions",
    "package_name": "",
    "methods": [
        {
            "docstring": "",
            "name": "__init__",
            "namespace": "django.db.migrations.exceptions.NodeNotFoundError.__init__",
            "class_name": "",
            "module_name": "",
            "package_name": ""
        },
        {
            "docstring": "",
            "name": "__str__",
            "namespace": "django.db.migrations.exceptions.NodeNotFoundError.__str__",
            "class_name": "",
            "module_name": "",
            "package_name": ""
        },
        {
            "docstring": "",
            "name": "__repr__",
            "namespace": "django.db.migrations.exceptions.NodeNotFoundError.__repr__",
            "class_name": "",
            "module_name": "",
            "package_name": ""
        }
    ]
}