{
    "docstring": "",
    "name": "GDALException",
    "namespace": "django.contrib.gis.gdal.error.GDALException",
    "module_name": "django.contrib.gis.gdal.error",
    "package_name": "",
    "methods": []
}